import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def make_graph(stock_data, revenue_data, stock_name):
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue"),
        vertical_spacing=0.3
    )

    stock_data_filtered = stock_data[stock_data["Date"] <= "2021-06-14"]
    revenue_data_filtered = revenue_data[revenue_data["Date"] <= "2021-06-14"]

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(stock_data_filtered["Date"]),
            y=stock_data_filtered["Close"].astype(float),
            name="Share Price"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(revenue_data_filtered["Date"]),
            y=revenue_data_filtered["Revenue"].astype(float),
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue (USD Millions)", row=2, col=1)

    fig.update_layout(
        showlegend=False,
        height=900,
        title=stock_name,
        xaxis_rangeslider_visible=True
    )

    fig.show()


# Load Tesla stock price data
tesla = yf.Ticker("TSLA")
tesla_share_price_data = tesla.history(period="max")

# Reset index so Date becomes a column
tesla_share_price_data.reset_index(inplace=True)

# Preview the dataset
tesla_share_price_data.head()

In [ ]:
tesla_data.head()

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume]
Index: []

In [ ]:
# Retrieve Tesla stock price data
tesla = yf.Ticker("TSLA")
tesla_share_price_data = tesla.history(period="max")

# Reset index so that the Date becomes a column
tesla_share_price_data.reset_index(inplace=True)

# Display the first rows of the dataset
tesla_share_price_data.head()

In [ ]:
# Retrieve Tesla revenue data from HTML page

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

# Send HTTP request to retrieve the HTML page
response = requests.get(url)

# Store the HTML content
html_data = response.text

In [ ]:
# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_data, "html.parser")

In [ ]:
# Create DataFrame to store Tesla revenue data
tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

In [ ]:
# Retrieve Tesla revenue HTML page

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

# Send HTTP request
response = requests.get(url)

# Raise error if request failed
response.raise_for_status()

# Store HTML content
html_data = response.text

In [ ]:
# Parse the HTML content
soup = BeautifulSoup(html_data, "html.parser")

# Extract all tables from the HTML page
tables = soup.find_all("table")

In [ ]:
from bs4 import BeautifulSoup

# HTML-Daten parsen mit BeautifulSoup und dem 'html.parser'
soup = BeautifulSoup(html_data, "html.parser")  # Du kannst auch 'html5lib' verwenden

# Überprüfen, ob die Daten geparst wurden
print("HTML-Daten wurden erfolgreich mit BeautifulSoup geparst!")

# Optional: Schön formatierte Ausgabe der HTML-Daten (nur für Debugging)
# print(soup.prettify())

In [ ]:
# Find all tables in the HTML page
tables = soup.find_all("table")

# Select the first table containing Tesla revenue data
tesla_table = tables[0]

In [ ]:
# List to store extracted data
data = []

# Find all tables in the HTML
tables = soup.find_all("table")

# Identify the table containing Tesla quarterly revenue
for table in tables:
    if "Tesla Quarterly Revenue" in str(table):
        target_table = table
        break

# Ensure the table was found
if "target_table" not in locals():
    raise ValueError("Tesla revenue table not found.")

# Extract rows from the table body
rows = target_table.find("tbody").find_all("tr")

for row in rows:
    cols = row.find_all("td")
    date = cols[0].text.strip()
    revenue = cols[1].text.strip()
    
    data.append({"Date": date, "Revenue": revenue})

# Create DataFrame
tesla_revenue = pd.DataFrame(data)

# Clean revenue column
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",|\$", "", regex=True)
tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].astype(float)

# Display preview
tesla_revenue.head()

In [ ]:
print(tesla_revenue)

          Date  Revenue
0   2022-09-30  21454.0
1   2022-06-30  16934.0
2   2022-03-31  18756.0
3   2021-12-31  17719.0
4   2021-09-30  13757.0
5   2021-06-30  11958.0
6   2021-03-31  10389.0
7   2020-12-31  10744.0
8   2020-09-30   8771.0
9   2020-06-30   6036.0
10  2020-03-31   5985.0
11  2019-12-31   7384.0
12  2019-09-30   6303.0
13  2019-06-30   6350.0
14  2019-03-31   4541.0
15  2018-12-31   7226.0
16  2018-09-30   6824.0
17  2018-06-30   4002.0
18  2018-03-31   3409.0
19  2017-12-31   3288.0
20  2017-09-30   2985.0
21  2017-06-30   2790.0
22  2017-03-31   2696.0
23  2016-12-31   2285.0
24  2016-09-30   2298.0
25  2016-06-30   1270.0
26  2016-03-31   1147.0
27  2015-12-31   1214.0
28  2015-09-30    937.0
29  2015-06-30    955.0
30  2015-03-31    940.0
31  2014-12-31    957.0
32  2014-09-30    852.0
33  2014-06-30    769.0
34  2014-03-31    621.0
35  2013-12-31    615.0
36  2013-09-30    431.0
37  2013-06-30    405.0
38  2013-03-31    562.0
39  2012-12-31    306.0
40  2012-09-30     50.0
41  2012-06-30     27.0
42  2012-03-31     30.0
43  2011-12-31     39.0
44  2011-09-30     58.0
45  2011-06-30     58.0
46  2011-03-31     49.0
47  2010-12-31     36.0
48  2010-09-30     31.0
49  2010-06-30     28.0
50  2010-03-31     21.0
52  2009-09-30     46.0
53  2009-06-30     27.0

In [ ]:
# Display the last 5 rows of the Tesla revenue DataFrame
tesla_revenue.tail()

          Date  Revenue
48  2010-09-30     31.0
49  2010-06-30     28.0
50  2010-03-31     21.0
52  2009-09-30     46.0
53  2009-06-30     27.0

In [ ]:
tesla_revenue.head()

         Date  Revenue
0  2022-09-30  21454.0
1  2022-06-30  16934.0
2  2022-03-31  18756.0
3  2021-12-31  17719.0
4  2021-09-30  13757.0

In [ ]:
# Retrieve GameStop stock price data
gme = yf.Ticker("GME")

# Download historical price data
gme_stock_data = gme.history(period="max")

# Reset index so Date becomes a column
gme_stock_data.reset_index(inplace=True)

# Preview the dataset
gme_stock_data.head()

                               Open      High       Low     Close    Volume  \
Date
2002-02-13 00:00:00-05:00  1.620128  1.693350  1.603296  1.691667  76216000
2002-02-14 00:00:00-05:00  1.712707  1.716074  1.670626  1.683250  11021600
2002-02-15 00:00:00-05:00  1.683250  1.687458  1.658001  1.674834   8389600
2002-02-19 00:00:00-05:00  1.666418  1.666418  1.578047  1.607504   7410400
2002-02-20 00:00:00-05:00  1.615920  1.662210  1.603296  1.662210   6892800

                           Dividends  Stock Splits
Date
2002-02-13 00:00:00-05:00        0.0           0.0
2002-02-14 00:00:00-05:00        0.0           0.0
2002-02-15 00:00:00-05:00        0.0           0.0
2002-02-19 00:00:00-05:00        0.0           0.0
2002-02-20 00:00:00-05:00        0.0           0.0

In [ ]:
# Retrieve GameStop stock price data
gme = yf.Ticker("GME")

# Download historical stock data
gme_share_price_data = gme.history(period="max")

# Reset index so Date becomes a column
gme_share_price_data.reset_index(inplace=True)

# Preview the dataset
gme_share_price_data.head()

                               Open      High       Low     Close    Volume  \
Date
2002-02-13 00:00:00-05:00  1.620128  1.693350  1.603296  1.691667  76216000
2002-02-14 00:00:00-05:00  1.712707  1.716074  1.670626  1.683250  11021600
2002-02-15 00:00:00-05:00  1.683251  1.687459  1.658002  1.674834   8389600
2002-02-19 00:00:00-05:00  1.666418  1.666418  1.578047  1.607504   7410400
2002-02-20 00:00:00-05:00  1.615920  1.662210  1.603296  1.662210   6892800

                           Dividends  Stock Splits
Date
2002-02-13 00:00:00-05:00        0.0           0.0
2002-02-14 00:00:00-05:00        0.0           0.0
2002-02-15 00:00:00-05:00        0.0           0.0
2002-02-19 00:00:00-05:00        0.0           0.0
2002-02-20 00:00:00-05:00        0.0           0.0

In [ ]:
# Create ticker object for GameStop
gme = yf.Ticker("GME")

# Retrieve historical stock data
gme_share_price_data = gme.history(period="max")

# Reset index so Date becomes a column
gme_share_price_data.reset_index(inplace=True)

# Preview the dataset
gme_share_price_data.head()

                       Date      Open      High       Low     Close    Volume  \
0 2002-02-13 00:00:00-05:00  1.620128  1.693349  1.603295  1.691666  76216000
1 2002-02-14 00:00:00-05:00  1.712707  1.716074  1.670626  1.683250  11021600
2 2002-02-15 00:00:00-05:00  1.683250  1.687458  1.658001  1.674834   8389600
3 2002-02-19 00:00:00-05:00  1.666418  1.666418  1.578047  1.607504   7410400
4 2002-02-20 00:00:00-05:00  1.615920  1.662210  1.603296  1.662210   6892800

   Dividends  Stock Splits
0        0.0           0.0
1        0.0           0.0
2        0.0           0.0
3        0.0           0.0
4        0.0           0.0

In [ ]:
print(gme_data.head())

                       Date      Open      High       Low     Close    Volume  \
0 2002-02-13 00:00:00-05:00  1.620128  1.693349  1.603295  1.691666  76216000
1 2002-02-14 00:00:00-05:00  1.712707  1.716074  1.670626  1.683250  11021600
2 2002-02-15 00:00:00-05:00  1.683250  1.687458  1.658001  1.674834   8389600
3 2002-02-19 00:00:00-05:00  1.666418  1.666418  1.578047  1.607504   7410400
4 2002-02-20 00:00:00-05:00  1.615920  1.662210  1.603296  1.662210   6892800

   Dividends  Stock Splits
0        0.0           0.0
1        0.0           0.0
2        0.0           0.0
3        0.0           0.0
4        0.0           0.0

In [ ]:
# Retrieve GameStop revenue HTML page
url_2 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

# Send request and retrieve HTML content
response = requests.get(url_2)
response.raise_for_status()

html_data_2 = response.text

In [ ]:
# URL containing GameStop revenue data
url_2 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

# Retrieve HTML page
response = requests.get(url_2)
response.raise_for_status()
html_data_2 = response.text

# Parse HTML using BeautifulSoup
soup = BeautifulSoup(html_data_2, "html.parser")

# Extract revenue table
table = soup.find_all("table")[0]

# Convert HTML table to DataFrame
gme_revenue = pd.read_html(str(table))[0]

# Preview dataset
gme_revenue.head()

# Clean revenue column
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(",|\$", "", regex=True)

In [ ]:
print(gme_revenue.columns)

In [ ]:
# URL containing GameStop revenue data
url_2 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

# Retrieve HTML page
response = requests.get(url_2)
response.raise_for_status()
html_data_2 = response.text

# Parse HTML using BeautifulSoup
soup = BeautifulSoup(html_data_2, "html.parser")

# Extract tables
tables = soup.find_all("table")

# Select first table containing revenue data
table = tables[0]

# Convert HTML table to DataFrame
gme_revenue = pd.read_html(str(table))[0]

# Rename columns
gme_revenue.columns = ["Date", "Revenue"]

# Remove whitespace from column names
gme_revenue.columns = gme_revenue.columns.str.strip()

# Clean revenue column
gme_revenue["Revenue"] = gme_revenue["Revenue"].replace({"\\$": "", ",": ""}, regex=True)

# Preview dataset
gme_revenue.head()
gme_revenue.tail()

Index(['GameStop Annual Revenue (Millions of US $)', 'GameStop Annual Revenue (Millions of US $).1'], dtype='object')
   Date Revenue
0  2020    6466
1  2019    8285
2  2018    8547
3  2017    7965
4  2016    9364
    Date Revenue
11  2009    8806
12  2008    7094
13  2007    5319
14  2006    3092
15  2005    1843

In [ ]:
def make_graph(stock_data, revenue_data, stock_name):
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue"),
        vertical_spacing=0.3
    )

    stock_data_filtered = stock_data[stock_data["Date"] <= "2021-06-14"]
    revenue_data_filtered = revenue_data[revenue_data["Date"] <= "2021-06-14"]

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(stock_data_filtered["Date"]),
            y=stock_data_filtered["Close"].astype(float),
            name="Share Price"
        ),
        row=1,
        col=1
    )

    fig.add_trace(
        go.Scatter(
            x=pd.to_datetime(revenue_data_filtered["Date"]),
            y=revenue_data_filtered["Revenue"].astype(float),
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue (USD Millions)", row=2, col=1)

    fig.update_layout(
        showlegend=False,
        height=900,
        title=stock_name,
        xaxis_rangeslider_visible=True
    )

    fig.show()


# Create Tesla stock price and revenue visualization
make_graph(tesla_share_price_data, tesla_revenue, "Tesla")

In [ ]:
# Create visualization for GameStop stock price and revenue
make_graph(gme_share_price_data, gme_revenue, "GameStop")

In [ ]:
# Convert Date columns to datetime
gme_share_price_data["Date"] = pd.to_datetime(gme_share_price_data["Date"])
gme_revenue["Date"] = pd.to_datetime(gme_revenue["Date"])

In [ ]:
# Create GameStop stock price and revenue visualization
make_graph(gme_data, gme_revenue, "GameStop")